Scriptname MAG_AtronachForgeRecipesScript extends ActiveMagicEffect

Book Property MAG_SpellTomeConjureSkeletalDragon Auto
Book Property MAG_AtronachForgeRecipeSpecial04 Auto

FormList Property MAG_AtronachForgeSigilStoneRecipeList Auto
FormList Property MAG_AtronachForgeSigilStoneResultList Auto
FormList Property MAG_AtronachForgeSpecial04 Auto

GlobalVariable Property AtronachForgeRecipeChance Auto
GlobalVariable Property AtronachForgeRecipeChestChance Auto
GlobalVariable Property AtronachForgeRecipeUragChance Auto

LeveledItem Property MAG_LItemAtronachForgeSigilStoneRecipeListUrag Auto

Event OnEffectStart(Actor akTarget, Actor akCaster)

	AtronachForgeRecipeChance.SetValueInt(85)
	AtronachForgeRecipeChestChance.SetValueInt(65)
	AtronachForgeRecipeUragChance.SetValueInt(50)
	MAG_AtronachForgeSigilStoneRecipeList.AddForm(MAG_AtronachForgeSpecial04)
	MAG_AtronachForgeSigilStoneResultList.AddForm(MAG_SpellTomeConjureSkeletalDragon)
	MAG_LItemAtronachForgeSigilStoneRecipeListUrag.AddForm(MAG_AtronachForgeRecipeSpecial04, 1, 1)

EndEvent